name: ci

on: [push, workflow_dispatch]

jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      NODE_OPTIONS: '--max-old-space-size=3200'
    steps:
      - { uses: actions/checkout@v4, with: { persist-credentials: false } }
      - { uses: actions/setup-node@v4, with: { node-version: 'lts/*', cache: 'yarn' } }
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn test
