name: default

on: [push, workflow_dispatch]

jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      NODE_OPTIONS: '--max-old-space-size=3200'
    steps:
      - { uses: actions/checkout@v2, with: { persist-credentials: false } }
      - { uses: actions/setup-node@v1, with: { node-version: 14 } }
      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: deps-v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - { name: yarn, run: yarn --frozen-lockfile }

      - name: build
        run: yarn build

      - name: test
        run: yarn test-ci
