name: lighthouse

on:
  push:
    branches: [master, act]
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  lighthouse-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env: { NODE_OPTIONS: '--max-old-space-size=3200' }
    steps:
      - { uses: actions/checkout@v4, with: { persist-credentials: true } }
      - { uses: actions/setup-node@v4, with: { node-version: 'lts/*', cache: 'yarn' } }
      - run: yarn --frozen-lockfile

      - name: lhci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn lhci collect
          DEBUG=nc* yarn tsn persistLHReport.script
